### ISSUE TITLE
Seeking help to resolve an error when trying to install Mochi

### ISSUE THREAD

**Issue by jesunsahariar** [mochi-hpc/mochi-spack-packages#9]
Hi,

I am trying to execute the command `spack -d -v install mochi-thallium~cereal@0.8.3 '^mercury~boostsys' catch2@2.13.3 gortools@7.7` and ran into the following error `AttributeError: 'str' object has no attribute 'get'`.  I am also attaching the output log with spack verbose/debug mode enabled. The following are the currently loaded modules on the machine where I am encountering the problem: ` 1)python/miniconda3.9   2) gcc/9.1.0             3) openmpi/4.0.6         4) cmake/3.19.6`

I would greatly appreciate if you have any suggestion or feedback to address the issue. Please let me know if I can provide any additional information. Thanks in advance!

Best regards,
Jesun Firoz
[dependency_op.log](https://github.com/mochi-hpc/mochi-spack-packages/files/8383228/dependency_op.log)

**Comment by mdorier** [comment]
This looks like a Spack problem, not a Mochi problem. Can you make sure you have the latest release of spack, and an up-to-date clone of mochi-spack-packages, and try with something else than thallium? (e.g. zlib)

Also a couple of things: thallium 0.8.3 is pretty old, the latest is 0.10.0, and disabling cereal is not recommended since it will become a mandatory dependency in the future.

**Comment by jesunsahariar** [comment]
Thanks Matthieu, for your suggestions and feedbacks. I will try them out.

Best regards,
Jesun Firoz
